### ISSUE TITLE
On Solaris, Rational#** returns Infinity for Rational(0, 1) passed a negative Float FAILED

### ISSUE THREAD

**Issue by ngoto** [ruby/rubyspec#134]
On Solaris 10 running on SPARC architecture CPU, the following spec fails.

```
Rational#** returns Infinity for Rational(0, 1) passed a negative Float FAILED
Expected -1
 to equal 1
```

Source code of the spec is:
```
  it "returns Infinity for Rational(0, 1) passed a negative Float" do
    [-1.0, -3.0, -3.14].each do |exponent|
      (Rational(0, 1) ** exponent).infinite?.should == 1
    end
  end
```

When running the spec, Rational(0,1) is implicitly converted to Float value 0.0, and the libm function pow(0.0, -1.0) is called.

On Solaris, the return value of pow(0.0, -1.0) varies depending on compile-time options.

http://docs.oracle.com/cd/E37069_01/html/E39019/z4000ac610479.html

See "pow(0,x<0)" line in the Table E-1 about the return value of pow(0.0, -1.0).

By default (==X/Open, C90), pow(0.0, -1.0) returns -HUGE_VAL (== -Infinity in Ruby).

When "-xc99=all" or some equivalent options are given to CFLAGS, pow(0.0, -1.0) returns +Infinity, which is under C99 standards, and the spec passes without failure.

How do we treat the spec in such case?

**Comment by eregon** [comment]
This is a tricky one.

In general, I would say `libc`-dependent behavior should be specified in a way that is not reliant on a specific libc implementation.
I think the specs which fail because of old time zones or time zone changes fall into the same category.

One could of course argue Ruby should unify such system-dependent behavior, but in some cases it does not make much sense, particularly when the cases are degenerated and imprecise anyway.

@ngoto What do you think is better in this case? Have some conditional code for Solaris so that pow(+0,-1) returns +Inf or relax the spec to `(Rational(0, 1) ** exponent).abs.infinite?.should == 1` ?

Intuitively I would say -Infinity is an incorrect result because `0.0 ** -1.0` should be `1 / 0.0 == +Inf`.

**Comment by eregon** [comment]
I reported the issue on the Ruby tracker as it seems worth discussing in general.
https://bugs.ruby-lang.org/issues/11582

**Comment by eregon** [comment]
I added a guard to not test this on Solaris since the behavior is not consistently the same.
If this gets consistent in Ruby itself, we can of course always remove that guard or specify better what should be expected on Solaris.
https://bugs.ruby-lang.org/issues/11582 is there for reference.
