### ISSUE TITLE
Decision process of future rubyspec

### ISSUE THREAD

**Issue by nurse** [ruby/rubyspec#50]
Current rubyspec doesn't have its own decision process. I worry that rubyspec becomes patch works. As far as I understand rubyspec should decide coding style (how to write specific specs, what helpers should be added, and so on).
I think, rubyspec should also adopt the honest dictator model. People who want to change rubyspec will talk with the dictator.

How do you think?

**Comment by eregon** [comment]
Agreed, we need some coding style and rules.

I am not sure what you mean by "the honest dictator model", could you elaborate a bit?

I do think there should not be only one person able to accept changes in RubySpec, that is fundamental for me.
And I think coding style/rules should be established based on the existing ones and should be agreed by most concerned parties (MRI committers contributing to RubySpec and ideally active external contributors).

**Comment by anthonycrumley** [comment]
Concerning coding style, here are some links to the rubyspec website repo for current style which may be helpful.
* https://github.com/rubyspec/rubyspec.github.io/blob/archive/organization.markdown
* https://github.com/rubyspec/rubyspec.github.io/blob/archive/style_guide.markdown

Concerning project process, the process from the ZeroMQ community has a lot of ideas that I like (http://rfc.zeromq.org/spec:22).  The Ruby Rogues podcast interviewed the guy who leads the process (http://devchat.tv/ruby-rogues/188-rr-community-building-with-pieter-hintjens).  The most attractive part of it to me is the focus on growing the community and thereby speeding development of the project.

**Comment by nurse** [comment]
> I am not sure what you mean by "the honest dictator model", could you elaborate a bit?

Like Ruby or Rails, a decision is done by a person like matz or DHH. This is better than committee model on bikeshed issues like naming or styles, or fundamental issues like what should RubySpec cover, or fundamentally they must define "What is RubySpec". Of course they must consider concerned parties and resolve their conflicts.

In other words, they must handle nobu, who has his own vision.

**Comment by nurse** [comment]
For example, they must decide (or defer) #34 even if there are no comments.

**Comment by eregon** [comment]
@nurse I see, but like matz or DHH the honest dictator would not need to get involved for merging a straightforward change? Who would be that honest dictator?

**Comment by nurse** [comment]
@eregon Yes, daily merging don't need them. Who would be is difficult issue. I had expected brixen could be that...

**Comment by anthonycrumley** [comment]
I think that would be "Benevolent Dictator".  http://en.wikipedia.org/wiki/Benevolent_dictator_for_life

**Comment by anthonycrumley** [comment]
The person chosen for this role needs to be "Benevolent" enough to resolve conflict without creating more conflict.  Yet, they need to have a vision of what the project should be and make difficult decisions that some people won't like.  They need to be able to move the project along without causing detrimental forks.  

They also need to be a person who is able to build up a community around RubySpec because the Ruby language is vast in scope.  A significant group of developers is needed for RubySpec to realize its potential.

**Comment by anthonycrumley** [comment]
I like this definition of "Benevolent Dictator".  http://en.wiktionary.org/wiki/benevolent_dictator

**Comment by eregon** [comment]
I would like to propose myself as benevolent dictator of the new RubySpec at ruby/rubyspec.

Does someone else want this role?
It seems very clear brixen does not want it anymore at least.

My main goal is to augment contributions while maintaining good project standards in order to improve the coverage and the quality of the specs.

@nurse @hsbt @headius @anthonycrumley Do you agree with this?

**Comment by nurse** [comment]
Agree!

**Comment by anthonycrumley** [comment]
:+1:  Agree!

**Comment by hsbt** [comment]
Agreed!

**Comment by bruno-** [comment]
:+1:
long live rubyspec

**Comment by eregon** [comment]
I guess we can close this :smile:
