### ISSUE TITLE
SizedQueue not specified

### ISSUE THREAD

**Issue by anthonycrumley** [ruby/rubyspec#57]
SizedQueue behaves very much like Queue.  Shared behavior like that seems to be generally specified in a shared/queue folder where the individual objects are specified in library/queue and library/sizedqueue respectively.  The individual object specifications then use it_behaves_like for the shared behavior.

Is this the way to specify two very similar objects like this or is there another way?

This is how I plan to proceed with specifying SizedQueue unless a better way is shown.

**Comment by eregon** [comment]
Maybe they should be in library/thread/queue and library/thread/sizedqueue (and share in library/thread/shared) since
```ruby
ruby -rthread -e 'p Queue' # Thread::Queue
```
(they are not part of core, rubygems loads the thread library)

`mkspec` (from mspec) can be used to generate the initial files:
```
../mspec/bin/mkspec -rthread -c Thread::Queue --base library
../mspec/bin/mkspec -rthread -c Thread::SizedQueue --base library
```
Using `it_behaves_like` is indeed the recommended way AFAIK to share specs. Sharing this way tends to make the specs harder to read and they often need to use more metaprogramming like `send`, but in this case it's a perfectly good use case.
And then specify in each file potential divergences from that.

(I think sharing for aliases is not ideal, but that's another discussion)

**Comment by anthonycrumley** [comment]
Thanks for the feedback.  :smile: 

It looks like Queue and SizedQueue moved to core in 2.2.

http://ruby-doc.org/core-2.2.1/Queue.html
http://ruby-doc.org/core-2.2.1/Queue.html

I'm not sure what to do when things move around like that between versions.  Which ever place we put them, core or library, it will be wrong in some versions of Ruby.  Maybe they should be moved to the place that they belong is the most recent version of Ruby which would be core in this case.  Do you think we should move them or leave them alone?

**Comment by eregon** [comment]
I think they are not in core, this is probably a bug of rdoc or ruby-doc.org.
There is some ongoing discussion about it though: https://bugs.ruby-lang.org/issues/8919 but it seems it is not yet done.
Same goes for ConditionVariable by the way, which I think might be worth specifying (its behavior is rather surprising compared to typical implementations in that it allows to be associated with multiple mutexes).
```
$ ruby -v --disable-gem -e 'p Queue'
ruby 2.3.0dev (2015-03-21 trunk 50043) [x86_64-linux]
-e:1:in `<main>': uninitialized constant Queue (NameError)

$ ruby -v -e 'p Queue; puts $"'
Thread::Queue
...
/opt/rubies/ruby-trunk/lib/ruby/2.3.0/x86_64-linux/thread.so
...
```
So rubygems requires 'thread', in lib/rubygems.rb.
They get aliased in Object, so `Queue = Thread::Queue` but this is a separate concern.
So, definitely part of library/. If it changes we'll eventually move them.

**Comment by anthonycrumley** [comment]
Thanks for clarifying all that!!  I will put them under library/thread.

**Comment by anthonycrumley** [comment]
Completed by #59.
